project:
  type: website

website:
  title: "dhblog"
  navbar:
    right:
      - about.qmd

      - icon: twitter
        href: https://twitter.com/DienhoaT
      - icon: linkedin
        href: https://www.linkedin.com/in/dien-hoa-truong-74449aa4/
      - icon: github
        href: https://github.com/dienhoa
format:
  html:
    theme: litera
    css: styles.css



